import {WordInterface} from "./word.model";

const ENGLISH_WORDS_GAME: Record<string, string> = {
  'Bag jumping': 'nhảy bao bố',
  'Human chess': 'cờ người',
  'Cat and mouse game': 'mèo đuổi chuột',
  'Bamboo jacks': 'đánh chuyền, chắt chuyền',
  'Hopscotch': 'nhảy lò cò',
  'Rice cooking competition': 'thi thổi cơm',
  'Wrestling': 'trò đấu vật',
  'Throwing cotton ball game': 'ném còn',
  'Mandarin Square Capturing': 'ô ăn quan',
  'Cock fighting': 'chọi gà/trâu',
  'Horse jumping': 'trò nhảy ngựa',
  'Blind mans buff': 'bịt mắt bắt dê',
  'Dragon snake': 'rồng rắn lên mây',
  'Bamboo dancing': 'nhảy sạp',
  'Swaying back and forth game': 'chơi đánh đu',
  'Hide and seek': 'trốn tìm',
  'Marbles': 'trò chơi bi',
  'Tug of war': 'kéo co',
  'Flying kite': 'thả diều',
  'Mud banger': 'pháo đất',
  'Spinning tops': 'bổ quay',
  'Chanting while sawing wood': 'kéo cưa lừa xẻ',
  'Stilt walking': 'đi cà kheo',
  'Go': 'cờ vây (tiếng Nhật: Igo)',
  'Board game': 'trò chơi xúc xắc',
  'Table football': 'Bi lắc',
  'Backgammon': 'cờ thỏ cáo',
  'Puzzle piece': 'Mảnh ghép',
  'Card': 'Chơi bài',
  'Video game': 'Trò chơi trên máy',
  'Chess': 'cờ vua',
  'Dice': 'súc sắc/ die: con súc sắc',
  'Puzzle': 'Trò ghép hình',
  'Chips': 'Chơi xèng',
  'Draughts': 'cờ đam',
  'Bridge': 'trò đánh bài brit',
  'To deal the cards': 'chia bài',
'Blackjack': 'trò (chơi ở casino) đánh bài blackjack',
'card': 'quân bài',
'To cut the cards': 'chia bài thành 2 phần sau đó trộn',
'Hand': 'xấp bài có trên tay',
'Pack of cards': 'bộ bài',
'To shuffle the cards': 'trộn bài',
'Your turn ': 'đến lượt bạn',
'Hearts': 'quân cơ',
'Poker': 'trò đánh bài xì/tú lơ khơ',
'Trick': 'ván bài',
'Clubs': 'quân nhép',
'Suit': 'bộ bài',
'Monopoly': 'cờ tỷ phú',
'Jenga': 'trò chơi rút gỗ',
'Uno': 'trò chơi bài Uno',
'The Werewolves of Millers Hollow': 'ma sói',
'Exploding kittens': 'mèo nổ',
'Scrabble': 'trò chơi xếp chữ',
'Ludo': 'cờ cá ngựa',
'Hangman': 'trò chơi đoán chữ/người treo cổ',
'Countdown': 'trò chơi đếm ngược',
'Bingo': 'trò chơi Bingo',
'Pictionary': 'trò đoán chữ qua hình ảnh',
}

const ENGLISH_WORDS_FEELING: Record<string, string> = {
  'Amused': 'vui vẻ',
  'Delighted': 'rất hạnh phúc',
  'Enthusiastic': 'nhiệt tình',
  'Excited': 'phấn khích, hứng thú',
  'Ecstatic': 'vô cùng hạnh phúc',
  'Confident': 'tự tin',
  'Surprised': 'ngạc nhiên',
  'Great': 'tuyệt vời',
  'Happy': 'hạnh phúc',
  'Over the moon': 'rất sung sướng',
  'Overjoyed': 'cực kỳ hứng thú.',
  'Positive': 'lạc quan',
  'Relaxed': 'thư giãn, thoải mái',
  'Wonderful': 'tuyệt vời',
  'Terrific': 'tuyệt vời',
  'Angry': 'tức giận',
  'Anxious': 'lo lắng',
  'Annoyed': 'bực mình',
  'Appalled': 'rất sốc',
  'Apprehensive': 'hơi lo lắng',
  'Arrogant': 'kiêu ngạo',
  'Ashamed': 'xấu hổ',
  'Bewildered': 'rất bối rối',
  'Bored': 'chán',
  'Confused': 'lúng túng',
  'Depressed': 'rất buồn',
  'Disappointed': 'thất vọng',
  'Emotional': 'dễ bị xúc động',
  'Envious': 'thèm muốn, đố kỵ',
  'Embarrassed': 'xấu hổ',
  'Frightened': 'sợ hãi',
  'Frustrated': 'tuyệt vọng',
  'Furious': 'giận giữ, điên tiết',
  'Horrified': 'sợ hãi',
  'Hurt': 'tổn thương',
  'Irritated': 'khó chịu',
  'Intrigued': 'hiếu kỳ',
  'Jealous': 'ganh tị',
  'Cheated': 'bị lừa',
  'Jaded': 'chán ngấy',
  'Let down let': 'thất vọng',
  'Malicious': 'ác độc',
  'Negative': 'tiêu cực; bi quan',
  'Overwhelmed': 'choáng ngợp',
  'Reluctant': 'miễn cưỡng',
  'Sad': 'buồn',
  'Scared': 'sợ hãi',
  'Seething': 'rất tức giận nhưng giấu kín',
  'Stressed': 'mệt mỏi',
  'Suspicious': 'đa nghi, ngờ vực',
  'Terrible': 'ốm hoặc mệt mỏi',
  'Terrified': 'rất sợ hãi',
  'Tense': 'căng thẳng',
  'Thoughtful': 'trầm tư',
  'Tired': 'mệt',
  'Upset': 'tức giận hoặc không vui',
  'Unhappy': 'buồn',
  'Victimised': 'cảm thấy bạn là nạn nhân của ai hoặc cái gì đó',
  'Worried': 'lo lắng',
  'Nonplussed': 'ngạc nhiên đến nỗi không biết phải làm gì',
}

const ENGLISH_WORDS_FRUIT: Record<string, string> = {
'Orange': 'trái cam',
'Apple': 'trái táo',
'Grape': 'trái nho',
'Banana': 'trái chuối',
'Avocado': 'trái bơ',
'Grapefruit': '(pomelo) quả bưởi',
'Mangosteen': 'quả măng cụt',
'Mango': 'quả xoài',
'Pineapple': 'quả dứa (trái thơm)',
'Starfruit': 'quả khế',
'Mandarin': 'quả quýt',
'Kiwi fruit': 'quả kiwi',
'Kumquat': 'quả quất',
'Jackfruit': 'quả mít',
'Papaya': 'quả đu đủ',
'Lemon': 'quả chanh vàng',
'Lime': 'trái chanh vỏ xanh',
'Durian': 'quả sầu riêng',
'Soursop': 'trái mãng cầu xiêm',
'Custard apple': 'trái mãng cầu (na)',
'Apricot': 'quả mơ',
'Coconut': 'quả dừa',
'Peach': 'quả đào',
'Cherry': 'quả anh đào',
'Sapota': 'trái sapôchê',
'Rambutan': 'trái chôm chôm',
'Dragon fruit': 'quả thanh long',
'Guava': 'quả ổi',
'Pear': 'quả lê',
'Longan': 'quả nhãn',
'Plum': 'trái mận',
'Melon': 'quả dưa',
'Watermelon': 'quả dưa hấu',
'Lychee': 'quả vải',
'Berry': 'quả dâu',
'Pomegranate': 'quả lựu',
'Persimmon': 'quả hồng',
'Strawberry': 'quả dâu tây',
'Passion fruit': 'quả chanh dây',
'Fig': 'quả sung',
'Green almonds': 'quả hạnh xanh',
'Cranberry': 'quả nam việt quất',
'Jujube': 'quả táo ta',
'Dates': 'quả chà là',
'Tamarind': 'quả me',
'Ugli fruit': 'quả chanh vùng Tây Ấn',
'Citron': 'quả thanh yên',
'Currant': 'quả nho Hy Lạp',
'Ambarella': 'quả cóc',
'Indian cream cobra melon': 'quả dưa gang',
'Granadilla': 'quả dưa Tây',
'Cantaloupe': 'quả dưa vàng',
'Honeydew': 'quả dưa xanh',
'Malay apple': 'quả điều',
'Star apple': 'quả vú sữa',
'Almond': 'quả hạnh',
'Chestnut': 'quả hạt dẻ',
'Honeydew melon': 'quả dưa bở ruột xanh',
'Blackberries': 'quả mâm xôi đen',
'Raisin': 'quả nho khô',
}

export const ENGLISH_WORDS_MUSIC: Record<string, string> = {
'Blue': 'nhạc buồn',
'Classical': 'nhạc cổ điển',
'Country': 'nhạc đồng quê',
'Dance': 'nhạc nhảy',
'Easy listening': 'nhạc dễ nghe',
'Electronic': 'nhạc điện tử',
'Folk': 'nhạc dân ca',
'Heavy metal': 'nhạc rock mạnh',
'Hip hop': 'nhạc hip hop',
'Jazz': 'nhạc jazz',
'Latin': 'nhạc latin',
'Opera': 'nhạc thính phòng',
'Pop': 'nhạc Pop',
'Rap': 'nhạc Rap',
'Reggae': 'nhạc reggaeton',
'Rock': 'nhạc rock',
'Techno': 'nhạc khiêu vũ',
'R&B': 'nhạc R&B',
'Band': 'ban nhạc',
'Brass band': 'ban nhạc kèn đồng',
'Choir': 'dàn hợp xướng',
'Concert band': 'ban nhạc biểu diễn trong buổi hòa nhạc',
'Jazz band': 'ban nhạc jazz',
'Orchestra': 'dàn nhạc giao hưởng',
'Pop Group': 'nhóm nhạc Pop',
'Rock Band': 'ban nhạc rock',
'String quartet': 'nhóm nhạc tứ tấu đàn dây',
'Composer': 'nhà soạn nhạc',
'Musician': 'nhạc công',
'Performer': 'nghệ sĩ biểu diễn',
'Bassist hoặc bass player': 'người chơi guitar bass',
'Cellist': 'người chơi vi-o-long-xen',
'Conductor': 'người chỉ huy dàn nhạc',
'DJ': 'người phối nhạc',
'Drummer': 'người chơi trống',
'Flautist': 'người thổi sáo',
'Guitarist': 'người chơi guitar',
'Keyboard player': 'người chơi keyboard',
'Pianist': 'người chơi piano',
'Organist': 'người chơi đàn organ',
'Pop star': 'ngôi sao nhạc Pop',
'Saxophonist': 'người thổi kèn saxophone',
'Trumpeter': 'người thổi kèm trumpet',
'Singer': 'ca sĩ',
'Alto': 'giọng nữ cao',
'Soprano': 'giọng nữ trầm',
'Bass': 'giọng nam trầm',
'Tenor': 'giọng nam cao',
'Baritone': 'giọng nam trung',
'Accord': 'hợp âm',
'Adagio': 'chậm, thong thả, khoan thai, tình cảm',
'Beat': 'nhịp trống',
'Harmony': 'hòa âm',
'Lyrics': 'lời bài hát',
'Melody hoặc tune': 'giai điệu',
'Note': 'nốt nhạc',
'Rhythm': 'nhịp điệu',
'Scale': 'Gam',
'Solo': 'đơn ca',
'Duet': 'biểu diễn đôi, song ca',
'In tune': 'đúng tông',
'Out of tune': 'lệch tông',
'To listen to music': 'nghe nhạc',
'To play an instrument': 'chơi nhạc cụ',
'To record': 'thu âm',
'Audience': 'khán giá',
'Concert': 'buổi hòa nhạc',
'Hymn': 'thánh ca',
'National anthem': 'quốc ca',
'Symphony': 'nhạc giao hưởng',
'Recording': 'bản thu âm',
}

function format(ENGLISH_WORDS: Record<string, string>): WordInterface[] {
  const arrayOfObjects: WordInterface[] = [];

  for (const key in ENGLISH_WORDS) {
    arrayOfObjects.push({en: key, vi: ENGLISH_WORDS[key]});
  }
  return arrayOfObjects;
}

export const GAME_LIST: WordInterface[] = format(ENGLISH_WORDS_GAME);
export const FEELING_LIST: WordInterface[] = format(ENGLISH_WORDS_FEELING);
export const FRUIT_LIST: WordInterface[] = format(ENGLISH_WORDS_FRUIT);
export const MUSIC_LIST: WordInterface[] = format(ENGLISH_WORDS_MUSIC);
